do $$
declare
  constraint_name text;
begin
  if to_regclass('public.profiles') is not null then
    execute 'alter table public.profiles drop constraint if exists profiles_id_fkey';
    for constraint_name in
      select c.conname
      from pg_constraint c
      join pg_class t on t.oid = c.conrelid
      join pg_namespace n on n.oid = t.relnamespace
      where n.nspname = 'public'
        and t.relname = 'profiles'
        and c.contype = 'f'
        and pg_get_constraintdef(c.oid) ilike '%references%users%'
    loop
      execute format('alter table public.profiles drop constraint if exists %I', constraint_name);
    end loop;
  end if;
  if to_regclass('public.profiles') is not null
     and not exists (
       select 1 from pg_constraint c
       join pg_class t on t.oid = c.conrelid
       join pg_namespace n on n.oid = t.relnamespace
       where n.nspname = 'public'
         and t.relname = 'profiles'
         and c.conname = 'profiles_id_fkey'
     ) then
    alter table public.profiles
      add constraint profiles_id_fkey
      foreign key (id) references auth.users(id) on delete cascade;
  end if;
end $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and is_admin = true); $$;
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.resident_profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, room_number text, access_until date, person_type text not null default 'hostel resident' check (person_type in ('hostel resident','room guest','outside hostel')), active boolean not null default true, qr_token uuid not null default gen_random_uuid() unique, created_at timestamptz not null default now());
create table if not exists public.checkins (id bigint generated by default as identity primary key, resident_id uuid not null references public.resident_profiles(id) on delete cascade, scanned_by uuid not null references auth.users(id), scanned_at timestamptz not null default now(), meal_period text not null, entry_status text not null default 'eligible');
alter table public.resident_profiles enable row level security;
alter table public.checkins enable row level security;
drop policy if exists "Residents can view own profile" on public.resident_profiles;
create policy "Residents can view own profile" on public.resident_profiles for select using (auth.uid() = id);
drop policy if exists "Admins can manage resident profiles" on public.resident_profiles;
create policy "Admins can manage resident profiles" on public.resident_profiles for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins can view checkins" on public.checkins;
create policy "Admins can view checkins" on public.checkins for select using (public.is_admin());
drop policy if exists "Admins can record checkins" on public.checkins;
create policy "Admins can record checkins" on public.checkins for insert with check (public.is_admin());
create index if not exists checkins_scanned_at_idx on public.checkins (scanned_at desc);
create index if not exists resident_profiles_qr_token_idx on public.resident_profiles (qr_token);
insert into public.profiles (id, is_admin)
select id, true
from auth.users
where lower(email) in ('amoghblue333@gmail.com', 'amoghsuresh3@gmail.com')
on conflict (id) do update set is_admin = true;
