const SUPABASE_URL='https://pklrwgdhwintkomkbuwt.supabase.co';
const SUPABASE_KEY='sb_publishable_KDCLOLGNWNeHJtryv6l2dg_SFExsUKZ';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const defaults={menu:{Monday:['Puttu + Kadala + Boost/Tea','Rice + Sambar + Egg burji','Chicken Biriyani + Raita'],Tuesday:['Upma + Robust + Tea','Rice + Fish curry + Thoran','Idiyappam/Appam + Green peas/Kadala + Black tea'],Wednesday:['Dosa + Tomato chutney + Tea/Coffee','Rice + Paripp curry + Chicken fry + Curd','Mandhi rice/Macaroni + Mayonnaise/Ketchup'],Thursday:['Puttu + Kadala / Idiyappam + Stew + Tea','Fish biriyani / Meals + Fish fry','Appam + Green peas/Kadala or Macaroni + Black tea'],Friday:['Upma + Robust + Black tea','Rice + Moru curry + Soyabean','Puttu + Chicken curry / Erachi chor'],Saturday:['Idli + Sambar + Tea','Sadhya + Payasam','Porotta + Egg curry/Chilli Gobi + Black tea'],Sunday:['Bread + Jam/Milkmaid + Tea','Ghee rice + Beef/Chicken curry + raita','Kanji + Payar + Pappad']},duty:{Monday:['Akhil Menon','Rahul Raj','Vishnu S','Nivin Jose','Arjun P'],Tuesday:['Adarsh K','Fasil M','Joel Thomas','Sreehari P','Yadhu Krishnan'],Wednesday:['Midhun V','Nikhil B','Anoop S','Rohan Mathew','Shyam Das'],Thursday:['Abhishek R','Amal Dev','Hari Krishnan','Jishnu K','Sanjay P'],Friday:['Kiran Kumar','Manu S','Naveen P','Roshan T','Sahil A'],Saturday:['Basil C','Dhanush R','Ebin Jose','Gokul M','Irfan K'],Sunday:['Jithin P','Kevin J','Lijo Varghese','Maneesh S','Nandu R']}};
const days=Object.keys(defaults.menu);let data=structuredClone(defaults);let selectedDay=days[(new Date().getDay()+6)%7];let isAdmin=false;
const $=s=>document.querySelector(s);function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
async function loadRemote(){if(!db)return;const [m,d,a]=await Promise.all([db.from('menu').select('*'),db.from('duty_roster').select('*'),db.from('announcements').select('*').order('created_at',{ascending:false}).limit(3)]);if(!m.error&&m.data?.length)m.data.forEach(r=>data.menu[r.day]=[r.breakfast,r.lunch,r.dinner]);if(!d.error&&d.data?.length)d.data.forEach(r=>data.duty[r.day]=r.residents);if(!a.error&&a.data?.length)renderNotices(a.data);render()}
const mealNames=['BREAKFAST','LUNCH','DINNER'];const mealSlots=[{start:8*60,end:8*60+45,time:'8:00 - 8:45 AM'},{start:12*60+5,end:12*60+50,time:'12:05 - 12:50 PM'},{start:19*60+45,end:20*60+30,time:'7:45 - 8:30 PM'}];
function todayName(){return days[(new Date().getDay()+6)%7]}
function mealIndexForNow(){const now=new Date();const minutes=now.getHours()*60+now.getMinutes();const current=mealSlots.findIndex(x=>minutes>=x.start&&minutes<=x.end);if(current!==-1)return current;const next=mealSlots.findIndex(x=>minutes<x.start);return next===-1?3:next}
function renderQuickTiming(){const card=document.querySelector('.quick-card');if(!card)return;let label='BREAKFAST',time=mealSlots[0].time;if(selectedDay===todayName()){const index=mealIndexForNow();if(index===3){label='TOMORROW · BREAKFAST';time=mealSlots[0].time}else{label=mealNames[index];time=mealSlots[index].time}}card.querySelector('small').textContent=label;card.querySelector('b').textContent=time;card.querySelector('.quick-icon').textContent=label.includes('DINNER')?'☾':label.includes('LUNCH')?'◷':'☕'}
function renderMeals(){const meals=data.menu[selectedDay];if(selectedDay!==todayName())return meals.map((meal,i)=>`<div class="meal"><label>${mealNames[i]}</label><p>${meal}</p></div>`).join('');const next=mealIndexForNow();const tomorrow=days[(days.indexOf(selectedDay)+1)%7];const current=next===3?`<div class="meal next-meal"><label>NEXT · TOMORROW BREAKFAST</label><p>${data.menu[tomorrow][0]}</p></div>`:`<div class="meal next-meal"><label>NEXT MEAL · ${mealNames[next]}</label><p>${meals[next]}</p></div>`;const past=meals.slice(0,next===3?3:next).map((meal,i)=>`<div class="past-meal"><label>${mealNames[i]}</label><p>${meal}</p></div>`).join('');return current+(past?`<details class="past-meals"><summary>Earlier meals today <span>＋</span></summary><div>${past}</div></details>`:'')}
function render(){ $('#heroDay').textContent=selectedDay.toUpperCase();$('#todayLabel').textContent=selectedDay===todayName()?'TODAY':'SELECTED DAY';$('#dutyDayTitle').textContent=`${selectedDay}'s team`;$('#weekStrip').innerHTML=days.map(d=>`<button class="day-btn ${d===selectedDay?'selected':''}" data-day="${d}"><small>${d.slice(0,3).toUpperCase()}</small>${d.slice(0,3)}</button>`).join('');renderQuickTiming();$('#mealCard').innerHTML=renderMeals();$('#dutyList').innerHTML=data.duty[selectedDay].map((n,i)=>`<div class="duty-person"><div class="avatar">${initials(n)}</div><div><b>${n}</b><span>${i===0?'Duty lead':'Mess duty'}</span></div></div>`).join('');let ni=(days.indexOf(selectedDay)+1)%7;$('#nextDutyText').textContent=`${days[ni]} · 5 residents`;document.querySelectorAll('.day-btn').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;render()});if(isAdmin)showAdminTools()}
function showAdminTools(){const v=$('#manageView');if(!v||$('#noticeAdmin'))return;v.insertAdjacentHTML('beforeend',`<div id="noticeAdmin" class="manage-card"><div><span class="manage-icon">✦</span><b>Notify residents</b><p>Publish an announcement to everyone.</p></div><button class="gold-btn" id="notifyBtn">Write</button></div>`);$('#notifyBtn').onclick=()=>$('#noticeDialog').showModal()}
function renderNotices(rows){const existing=$('#noticeFeed');if(existing)existing.remove();$('#menuView').insertAdjacentHTML('afterbegin',`<div id="noticeFeed" class="notice-feed"><div class="eyebrow">MESS UPDATES</div>${rows.map(r=>`<div class="notice-item"><b>${r.title}</b><p>${r.body}</p></div>`).join('')}</div>`)}
async function openEditor(kind){if(!isAdmin)return requireAdmin();const isMenu=kind==='menu';$('#dialogTitle').textContent=isMenu?'Edit menu':'Edit roster';$('#formFields').innerHTML=`<div class="dialog-body">${days.map(d=>`<div class="field"><label>${d} · ${isMenu?'meal items':'five resident names'}</label><input name="${d}" value="${(isMenu?data.menu[d]:data.duty[d]).join(' | ').replaceAll('"','&quot;')}" /></div>`).join('')}</div>`;$('#editDialog').showModal();$('#editForm').onsubmit=async e=>{e.preventDefault();days.forEach(d=>{const v=new FormData(e.target).get(d).split('|').map(x=>x.trim()).filter(Boolean);if(isMenu)data.menu[d]=v.slice(0,3);else data.duty[d]=v.slice(0,5)});for(const d of days){const r=isMenu?await db.from('menu').upsert({day:d,breakfast:data.menu[d][0],lunch:data.menu[d][1],dinner:data.menu[d][2]}):await db.from('duty_roster').upsert({day:d,residents:data.duty[d]});if(r.error){toast(r.error.message);return}}$('#editDialog').close();toast('Updated for everyone');render()}}
function requireAdmin(){$('#authError').textContent='Please sign in with an approved admin account.';$('#authDialog').showModal()}
async function setPassword(e){e.preventDefault();$('#passwordError').textContent='';if($('#newPassword').value!==$('#confirmPassword').value){$('#passwordError').textContent='Passwords do not match.';return}const r=await db.auth.updateUser({password:$('#newPassword').value});if(r.error){$('#passwordError').textContent=r.error.message;return}$('#passwordDialog').close();toast('Password saved');}
async function loadRegister(){if(!isAdmin)return;const r=await db.from('checkins').select('id,scanned_at,meal_period,entry_status,resident_profiles(full_name,room_number,person_type,access_until)').order('scanned_at',{ascending:false}).limit(50);const el=$('#entryRegister');if(r.error){el.innerHTML=`<p class="muted-copy">${r.error.message}</p>`;return}el.innerHTML=r.data?.length?`<div class="register-list">${r.data.map(x=>`<div class="register-row"><div><b>${x.resident_profiles?.full_name||'Unknown resident'}</b><span>Room ${x.resident_profiles?.room_number||'-'} · ${x.resident_profiles?.person_type||'resident'}</span></div><div><b>${new Date(x.scanned_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b><span>${x.meal_period||'Mess entry'}</span></div></div>`).join('')}</div>`:'<p class="muted-copy">No entries recorded yet.</p>'}
async function residentSignIn(e){e.preventDefault();$('#residentAuthError').textContent='';const email=$('#residentEmail').value.trim();const {error}=await db.auth.signInWithPassword({email,password:$('#residentPassword').value});if(error){$('#residentAuthError').textContent=error.message;return}const p=await db.rpc('get_my_resident_profile',{p_email:email});if(p.error||!p.data){await db.auth.signOut();$('#residentAuthError').textContent=p.error?.message||'No resident profile is linked to this account yet.';return}isAdmin=false;renderResidentPass(p.data);$('#residentAuthDialog').close();document.querySelector('[data-view=resident]').click();toast('QR pass ready')}
function renderResidentPass(p){$('#residentLocked').hidden=true;$('#residentPass').hidden=false;$('#residentName').textContent=p.full_name;$('#residentType').textContent=p.person_type||'Resident';$('#residentRoom').textContent=p.room_number||'-';$('#residentAccess').textContent=p.access_until||'Not set';const qr=$('#residentQr');const draw=()=>{qr.replaceChildren();if(!window.QRCode){qr.textContent='QR library unavailable. Reload the app.';return}const value=`SAGAR-HOSTEL|v1|${p.qr_token}`;if(typeof QRCode.toCanvas==='function'){const canvas=document.createElement('canvas');qr.appendChild(canvas);QRCode.toCanvas(canvas,value,{width:220,margin:2,color:{dark:'#1d1c18',light:'#ffffff'}},err=>{if(err)qr.textContent='Unable to render QR. Please reload.'})}else{new QRCode(qr,{text:value,width:220,height:220,colorDark:'#1d1c18',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}};window.QRCode?draw():setTimeout(draw,400)}
function openScanner(){if(!isAdmin)return requireAdmin();$('#scanResult').textContent='Point the camera at a resident QR code.';$('#scanDialog').showModal();if(window.Html5QrcodeScanner){window.entryScanner=new Html5QrcodeScanner('qrReader',{fps:10,qrbox:{width:220,height:220}},false);window.entryScanner.render(handleScan,()=>{})}else $('#scanResult').textContent='Scanner library is still loading. Please try again.'}
async function handleScan(decoded){if(window.entryScanner){await window.entryScanner.clear();window.entryScanner=null}const parts=decoded.split('|');const token=parts.length===3&&parts[0]==='SAGAR-HOSTEL'?parts[2]:decoded;const p=await db.from('resident_profiles').select('*').eq('qr_token',token).maybeSingle();if(p.error||!p.data){$('#scanResult').innerHTML='<b class="scan-denied">Not recognised</b><br>This QR is not registered.';return}const today=new Date().toISOString().slice(0,10);const eligible=p.data.active&&(!p.data.access_until||p.data.access_until>=today);if(!eligible){$('#scanResult').innerHTML=`<b class="scan-denied">Not eligible</b><br>${p.data.full_name} · access ended ${p.data.access_until||'inactive'}`;return}const meal=mealNames[Math.max(0,mealIndexForNow())]||'ENTRY';const saved=await db.rpc('record_checkin',{p_qr_token:token,p_meal_period:meal});if(saved.error){const denied=/expired|inactive|not eligible/i.test(saved.error.message);$('#scanResult').innerHTML=`<b class="scan-denied">${denied?'Not eligible':'Could not record'}</b><br>${saved.error.message}`;return}const checked=saved.data||p.data;$('#scanResult').innerHTML=`<b class="scan-ok">Eligible - entry recorded</b><br>${checked.full_name||p.data.full_name}<br>Room ${checked.room_number||p.data.room_number||'-'} · ${checked.person_type||p.data.person_type||'resident'}<br>Access until ${checked.access_until||p.data.access_until||'no expiry'}`;loadRegister()}
async function signIn(e){e.preventDefault();$('#authError').textContent='';const {data:res,error}=await db.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});if(error){$('#authError').textContent=error.message;return}const p=await db.rpc('is_admin');if(p.error){await db.auth.signOut();$('#authError').textContent=`Admin check failed: ${p.error.message}`;return}if(p.data===true){isAdmin=true;$('#authBtn').textContent='Sign out';$('#authDialog').close();document.querySelector('[data-view=manage]').click();toast('Admin mode enabled');loadRegister();render()}else{await db.auth.signOut();$('#authError').textContent='This account is not an approved admin.'}}
async function sendPasswordReset(){const email=$('#authEmail').value.trim();if(!email){$('#authError').textContent='Enter your admin email first.';return}const r=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('#authError').textContent=r.error?r.error.message:'Reset link sent. Check your email.'}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{if(t.dataset.view==='manage'&&!isAdmin)return requireAdmin();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$(`#${t.dataset.view}View`).classList.add('active-view')});$('#editMenuBtn').onclick=()=>openEditor('menu');$('#editDutyBtn').onclick=()=>openEditor('duty');$('#manageMenuBtn').onclick=()=>{document.querySelector('[data-view=menu]').click();openEditor('menu')};$('#manageDutyBtn').onclick=()=>{document.querySelector('[data-view=duty]').click();openEditor('duty')};$('#nextDay').onclick=()=>{selectedDay=days[(days.indexOf(selectedDay)+1)%7];render()};$('#jumpDuty').onclick=()=>{selectedDay=days[(days.indexOf(selectedDay)+1)%7];render()};$('#themeBtn').onclick=()=>document.body.classList.toggle('warm');$('#authBtn').onclick=()=>isAdmin?(db.auth.signOut().then(()=>{isAdmin=false;$('#authBtn').textContent='Admin login';document.querySelector('[data-view=menu]').click();render()})):$('#authDialog').showModal();$('#authForm').onsubmit=signIn;$('#noticeForm').onsubmit=async e=>{e.preventDefault();const r=await db.from('announcements').insert({title:$('#noticeTitle').value,body:$('#noticeBody').value});if(r.error){toast(r.error.message);return}$('#noticeDialog').close();e.target.reset();toast('Announcement published');loadRemote()};
$('#passwordForm').onsubmit=setPassword;if(db){db.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')$('#passwordDialog').showModal()});db.auth.getSession().then(async({data})=>{if(data.session){const admin=await db.rpc('is_admin');isAdmin=admin.data===true;$('#authBtn').textContent=isAdmin?'Sign out':'Admin login';if(isAdmin)loadRegister();else if(data.session.user.email){const resident=await db.rpc('get_my_resident_profile',{p_email:data.session.user.email});if(!resident.error&&resident.data)renderResidentPass(resident.data)}render()}});db.channel('mess-updates').on('postgres_changes',{event:'*',schema:'public',table:'menu'},loadRemote).on('postgres_changes',{event:'*',schema:'public',table:'duty_roster'},loadRemote).on('postgres_changes',{event:'INSERT',schema:'public',table:'announcements'},loadRemote).subscribe()}
render();loadRemote();
setInterval(render,60000);
$('#closeAuthBtn').onclick=()=>$('#authDialog').close();$('#closeEditBtn').onclick=()=>$('#editDialog').close();$('#closeNoticeBtn').onclick=()=>$('#noticeDialog').close();$('#resetPasswordBtn').onclick=sendPasswordReset;
$('#residentBtn').onclick=()=>$('#residentAuthDialog').showModal();$('#residentLoginBtn').onclick=()=>$('#residentAuthDialog').showModal();$('#closeResidentAuthBtn').onclick=()=>$('#residentAuthDialog').close();$('#residentAuthForm').onsubmit=residentSignIn;$('#scanEntryBtn').onclick=openScanner;$('#refreshRegisterBtn').onclick=loadRegister;$('#closeScanBtn').onclick=async()=>{if(window.entryScanner){await window.entryScanner.clear();window.entryScanner=null}$('#scanDialog').close()};
